version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: gatsby-plugin-mdx
    versions:
    - 1.10.0
    - 1.10.1
    - 1.9.0
    - 2.0.0
    - 2.0.1
    - 2.1.0
    - 2.2.0
    - 2.3.0
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.0
    - 2.32.10
    - 2.32.11
    - 2.32.2
    - 2.32.3
    - 2.32.4
    - 2.32.6
    - 2.32.8
    - 2.32.9
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.10.0
    - 3.10.1
    - 3.9.0
  - dependency-name: bl
    versions:
    - 4.0.3
    - 4.0.4
  - dependency-name: gatsby-plugin-typescript
    versions:
    - 2.11.0
    - 2.12.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.10.0
    - 2.11.0
  - dependency-name: gatsby-transformer-remark
    versions:
    - 2.15.0
    - 2.16.0
  - dependency-name: gatsby-plugin-page-creator
    versions:
    - 2.10.0
    - 2.9.0
  - dependency-name: prismjs
    versions:
    - 1.21.0
  - dependency-name: "@types/react-helmet"
    versions:
    - 6.1.0
